local M = {}

local emoji_list = {
	{ icon = "😀", name = "grinning", category = "face" },
	{ icon = "😃", name = "grinning_face_with_big_eyes", category = "face" },
	{ icon = "😄", name = "grinning_face_with_smiling_eyes", category = "face" },
	{ icon = "😁", name = "beaming_face_with_smiling_eyes", category = "face" },
	{ icon = "😅", name = "grinning_face_with_sweat", category = "face" },
	{ icon = "😂", name = "face_with_tears_of_joy", category = "face" },
	{ icon = "🤣", name = "rolling_on_the_floor_laughing", category = "face" },
	{ icon = "😊", name = "smiling_face_with_smiling_eyes", category = "face" },
	{ icon = "😇", name = "smiling_face_with_halo", category = "face" },
	{ icon = "🙂", name = "slightly_smiling_face", category = "face" },
	{ icon = "😉", name = "winking_face", category = "face" },
	{ icon = "😌", name = "relieved_face", category = "face" },
	{ icon = "😍", name = "heart_eyes", category = "face" },
	{ icon = "🥰", name = "smiling_face_with_hearts", category = "face" },
	{ icon = "😘", name = "face_blowing_a_kiss", category = "face" },
	{ icon = "😎", name = "smiling_face_with_sunglasses", category = "face" },
	{ icon = "🤔", name = "thinking_face", category = "face" },
	{ icon = "🤨", name = "face_with_raised_eyebrow", category = "face" },
	{ icon = "😐", name = "neutral_face", category = "face" },
	{ icon = "😑", name = "expressionless_face", category = "face" },
	{ icon = "😶", name = "face_without_mouth", category = "face" },
	{ icon = "😏", name = "smirking_face", category = "face" },
	{ icon = "😒", name = "unamused_face", category = "face" },
	{ icon = "🙄", name = "face_with_rolling_eyes", category = "face" },
	{ icon = "😬", name = "grimacing_face", category = "face" },
	{ icon = "🤥", name = "lying_face", category = "face" },
	{ icon = "😔", name = "pensive_face", category = "face" },
	{ icon = "😪", name = "sleepy_face", category = "face" },
	{ icon = "🤤", name = "drooling_face", category = "face" },
	{ icon = "😴", name = "sleeping_face", category = "face" },
	{ icon = "😷", name = "face_with_medical_mask", category = "face" },
	{ icon = "🤒", name = "face_with_thermometer", category = "face" },
	{ icon = "🤕", name = "face_with_head_bandage", category = "face" },
	{ icon = "🤢", name = "nauseated_face", category = "face" },
	{ icon = "🤮", name = "vomiting_face", category = "face" },
	{ icon = "🤧", name = "sneezing_face", category = "face" },
	{ icon = "🥵", name = "hot_face", category = "face" },
	{ icon = "🥶", name = "cold_face", category = "face" },
	{ icon = "🥴", name = "woozy_face", category = "face" },
	{ icon = "😵", name = "dizzy_face", category = "face" },
	{ icon = "🤯", name = "exploding_head", category = "face" },
	{ icon = "🤠", name = "cowboy_hat_face", category = "face" },
	{ icon = "🥳", name = "partying_face", category = "face" },
	{ icon = "🥸", name = "disguised_face", category = "face" },
	{ icon = "😎", name = "smiling_face_with_sunglasses", category = "face" },
	{ icon = "🤓", name = "nerd_face", category = "face" },
	{ icon = "🧐", name = "monocle_face", category = "face" },
	{ icon = "😕", name = "confused_face", category = "face" },
	{ icon = "😟", name = "worried_face", category = "face" },
	{ icon = "🙁", name = "slightly_frowning_face", category = "face" },
	{ icon = "😮", name = "face_with_open_mouth", category = "face" },
	{ icon = "😯", name = "hushed_face", category = "face" },
	{ icon = "😲", name = "astonished_face", category = "face" },
	{ icon = "😳", name = "flushed_face", category = "face" },
	{ icon = "🥺", name = "pleading_face", category = "face" },
	{ icon = "😦", name = "frowning_face_with_open_mouth", category = "face" },
	{ icon = "😧", name = "anguished_face", category = "face" },
	{ icon = "😨", name = "fearful_face", category = "face" },
	{ icon = "😰", name = "anxious_face_with_sweat", category = "face" },
	{ icon = "😥", name = "sad_but_relieved_face", category = "face" },
	{ icon = "😢", name = "crying_face", category = "face" },
	{ icon = "😭", name = "loudly_crying_face", category = "face" },
	{ icon = "😱", name = "face_screaming_in_fear", category = "face" },
	{ icon = "😖", name = "confounded_face", category = "face" },
	{ icon = "😣", name = "persevering_face", category = "face" },
	{ icon = "😞", name = "disappointed_face", category = "face" },
	{ icon = "😓", name = "downcast_face_with_sweat", category = "face" },
	{ icon = "😩", name = "weary_face", category = "face" },
	{ icon = "😫", name = "tired_face", category = "face" },
	{ icon = "🥱", name = "yawning_face", category = "face" },
	{ icon = "😤", name = "face_with_steam_from_nose", category = "face" },
	{ icon = "😡", name = "pouting_face", category = "face" },
	{ icon = "😠", name = "angry_face", category = "face" },
	{ icon = "🤬", name = "face_with_symbols_on_mouth", category = "face" },
	{ icon = "😈", name = "smiling_face_with_horns", category = "face" },
	{ icon = "👿", name = "angry_face_with_horns", category = "face" },
	{ icon = "💀", name = "skull", category = "face" },
	{ icon = "☠️", name = "skull_and_crossbones", category = "face" },
	{ icon = "💩", name = "pile_of_poo", category = "face" },
	{ icon = "🤡", name = "clown_face", category = "face" },
	{ icon = "👹", name = "ogre", category = "face" },
	{ icon = "👺", name = "goblin", category = "face" },
	{ icon = "👻", name = "ghost", category = "face" },
	{ icon = "👽", name = "alien", category = "face" },
	{ icon = "👾", name = "alien_monster", category = "face" },
	{ icon = "🤖", name = "robot", category = "face" },
	{ icon = "😺", name = "grinning_cat", category = "animal" },
	{ icon = "😸", name = "grinning_cat_with_smiling_eyes", category = "animal" },
	{ icon = "😹", name = "cat_with_tears_of_joy", category = "animal" },
	{ icon = "😻", name = "smiling_cat_with_heart_eyes", category = "animal" },
	{ icon = "😼", name = "cat_with_wry_smile", category = "animal" },
	{ icon = "😽", name = "kissing_cat", category = "animal" },
	{ icon = "🙀", name = "weary_cat", category = "animal" },
	{ icon = "😿", name = "crying_cat", category = "animal" },
	{ icon = "😾", name = "pouting_cat", category = "animal" },
	{ icon = "🙈", name = "see_no_evil_monkey", category = "animal" },
	{ icon = "🙉", name = "hear_no_evil_monkey", category = "animal" },
	{ icon = "🙊", name = "speak_no_evil_monkey", category = "animal" },
	{ icon = "🐶", name = "dog_face", category = "animal" },
	{ icon = "🐱", name = "cat_face", category = "animal" },
	{ icon = "🐭", name = "mouse_face", category = "animal" },
	{ icon = "🐹", name = "hamster", category = "animal" },
	{ icon = "🐰", name = "rabbit_face", category = "animal" },
	{ icon = "🦊", name = "fox", category = "animal" },
	{ icon = "🐻", name = "bear", category = "animal" },
	{ icon = "🐼", name = "panda", category = "animal" },
	{ icon = "🐨", name = "koala", category = "animal" },
	{ icon = "🐯", name = "tiger_face", category = "animal" },
	{ icon = "🦁", name = "lion", category = "animal" },
	{ icon = "🐮", name = "cow_face", category = "animal" },
	{ icon = "🐷", name = "pig_face", category = "animal" },
	{ icon = "🐸", name = "frog", category = "animal" },
	{ icon = "🐵", name = "monkey_face", category = "animal" },
	{ icon = "🙊", name = "speak_no_evil_monkey", category = "animal" },
	{ icon = "❤️", name = "red_heart", category = "symbol" },
	{ icon = "🧡", name = "orange_heart", category = "symbol" },
	{ icon = "💛", name = "yellow_heart", category = "symbol" },
	{ icon = "💚", name = "green_heart", category = "symbol" },
	{ icon = "💙", name = "blue_heart", category = "symbol" },
	{ icon = "💜", name = "purple_heart", category = "symbol" },
	{ icon = "🖤", name = "black_heart", category = "symbol" },
	{ icon = "🤍", name = "white_heart", category = "symbol" },
	{ icon = "🤎", name = "brown_heart", category = "symbol" },
	{ icon = "💔", name = "broken_heart", category = "symbol" },
	{ icon = "💕", name = "two_hearts", category = "symbol" },
	{ icon = "💞", name = "revolving_hearts", category = "symbol" },
	{ icon = "💓", name = "beating_heart", category = "symbol" },
	{ icon = "💗", name = "growing_heart", category = "symbol" },
	{ icon = "💖", name = "sparkling_heart", category = "symbol" },
	{ icon = "💘", name = "heart_with_arrow", category = "symbol" },
	{ icon = "💝", name = "heart_with_ribbon", category = "symbol" },
	{ icon = "✨", name = "sparkles", category = "symbol" },
	{ icon = "⭐", name = "star", category = "symbol" },
	{ icon = "🌟", name = "glowing_star", category = "symbol" },
	{ icon = "💫", name = "dizzy", category = "symbol" },
	{ icon = "🔥", name = "fire", category = "symbol" },
	{ icon = "💥", name = "collision", category = "symbol" },
	{ icon = "💢", name = "anger", category = "symbol" },
	{ icon = "💦", name = "sweat_droplets", category = "symbol" },
	{ icon = "💧", name = "droplet", category = "symbol" },
	{ icon = "💤", name = "zzz", category = "symbol" },
	{ icon = "👍", name = "thumbs_up", category = "gesture" },
	{ icon = "👎", name = "thumbs_down", category = "gesture" },
	{ icon = "👏", name = "clapping_hands", category = "gesture" },
	{ icon = "🙌", name = "raising_hands", category = "gesture" },
	{ icon = "🤝", name = "handshake", category = "gesture" },
	{ icon = "🙏", name = "folded_hands", category = "gesture" },
	{ icon = "✌️", name = "victory_hand", category = "gesture" },
	{ icon = "🤞", name = "crossed_fingers", category = "gesture" },
	{ icon = "🤙", name = "call_me_hand", category = "gesture" },
	{ icon = "👌", name = "ok_hand", category = "gesture" },
	{ icon = "👈", name = "point_left", category = "gesture" },
	{ icon = "👉", name = "point_right", category = "gesture" },
	{ icon = "👆", name = "point_up", category = "gesture" },
	{ icon = "👇", name = "point_down", category = "gesture" },
	{ icon = "☝️", name = "point_up_2", category = "gesture" },
	{ icon = "✋", name = "raised_hand", category = "gesture" },
	{ icon = "🤚", name = "raised_back_of_hand", category = "gesture" },
	{ icon = "🖐️", name = "hand_with_fingers_splayed", category = "gesture" },
	{ icon = "🖖", name = "vulcan_salute", category = "gesture" },
	{ icon = "💅", name = "nail_polish", category = "gesture" },
	{ icon = "🤳", name = "selfie", category = "gesture" },
	{ icon = "💪", name = "flexed_biceps", category = "gesture" },
	{ icon = "🧠", name = "brain", category = "body" },
	{ icon = "👀", name = "eyes", category = "body" },
	{ icon = "👁️", name = "eye", category = "body" },
	{ icon = "👅", name = "tongue", category = "body" },
	{ icon = "👄", name = "mouth", category = "body" },
	{ icon = "👋", name = "waving_hand", category = "gesture" },
	{ icon = "🤚", name = "raised_back_of_hand", category = "gesture" },
	{ icon = "🖕", name = "middle_finger", category = "gesture" },
	{ icon = "💪", name = "flexed_biceps", category = "gesture" },
	{ icon = "🏃", name = "running", category = "activity" },
	{ icon = "🚶", name = "walking", category = "activity" },
	{ icon = "🧘", name = "person_in_lotus_position", category = "activity" },
	{ icon = "🛀", name = "person_in_bed", category = "activity" },
	{ icon = "🎉", name = "party_popper", category = "object" },
	{ icon = "🎊", name = "confetti_ball", category = "object" },
	{ icon = "🎈", name = "balloon", category = "object" },
	{ icon = "🎁", name = "wrapped_gift", category = "object" },
	{ icon = "🎀", name = "ribbon", category = "object" },
	{ icon = "🏆", name = "trophy", category = "object" },
	{ icon = "🥇", name = "1st_place_medal", category = "object" },
	{ icon = "🥈", name = "2nd_place_medal", category = "object" },
	{ icon = "🥉", name = "3rd_place_medal", category = "object" },
	{ icon = "⚽", name = "soccer_ball", category = "object" },
	{ icon = "🏀", name = "basketball", category = "object" },
	{ icon = "🏈", name = "american_football", category = "object" },
	{ icon = "⚾", name = "baseball", category = "object" },
	{ icon = "🎾", name = "tennis", category = "object" },
	{ icon = "🎱", name = "8_ball", category = "object" },
	{ icon = "🏐", name = "volleyball", category = "object" },
	{ icon = "🏉", name = "rugby_football", category = "object" },
	{ icon = "🎳", name = "bowling", category = "object" },
	{ icon = "⛳", name = "flag_in_hole", category = "object" },
	{ icon = "🎮", name = "video_game", category = "object" },
	{ icon = "🎰", name = "slot_machine", category = "object" },
	{ icon = "💻", name = "laptop", category = "object" },
	{ icon = "🖥️", name = "desktop_computer", category = "object" },
	{ icon = "⌨️", name = "keyboard", category = "object" },
	{ icon = "🖱️", name = "computer_mouse", category = "object" },
	{ icon = "📱", name = "mobile_phone", category = "object" },
	{ icon = "📲", name = "calling_mobile_phone", category = "object" },
	{ icon = "☎️", name = "telephone", category = "object" },
	{ icon = "📞", name = "telephone_receiver", category = "object" },
	{ icon = "📟", name = "pager", category = "object" },
	{ icon = "📠", name = "fax_machine", category = "object" },
	{ icon = "📺", name = "television", category = "object" },
	{ icon = "📻", name = "radio", category = "object" },
	{ icon = "🎙️", name = "studio_microphone", category = "object" },
	{ icon = "🎚️", name = "level_slider", category = "object" },
	{ icon = "🎛️", name = "control_knobs", category = "object" },
	{ icon = "⏱️", name = "stopwatch", category = "object" },
	{ icon = "⏲️", name = "timer_clock", category = "object" },
	{ icon = "⏰", name = "alarm_clock", category = "object" },
	{ icon = "🕰️", name = "mantelpiece_clock", category = "object" },
	{ icon = "⌛", name = "hourglass", category = "object" },
	{ icon = "⏳", name = "hourglass_flowing_sand", category = "object" },
	{ icon = "🔋", name = "battery", category = "object" },
	{ icon = "🔌", name = "electric_plug", category = "object" },
	{ icon = "💡", name = "light_bulb", category = "object" },
	{ icon = "🔦", name = "flashlight", category = "object" },
	{ icon = "🕯️", name = "candle", category = "object" },
	{ icon = "🧯", name = "fire_extinguisher", category = "object" },
	{ icon = "🗝️", name = "old_key", category = "object" },
	{ icon = "🔨", name = "hammer", category = "object" },
	{ icon = "🪓", name = "axe", category = "object" },
	{ icon = "⛏️", name = "pick", category = "object" },
	{ icon = "🔧", name = "wrench", category = "object" },
	{ icon = "🔩", name = "nut_and_bolt", category = "object" },
	{ icon = "⚙️", name = "gear", category = "object" },
	{ icon = "🗜️", name = "clamp", category = "object" },
	{ icon = "⚖️", name = "balance_scale", category = "object" },
	{ icon = "🔗", name = "link", category = "object" },
	{ icon = "⛓️", name = "chains", category = "object" },
	{ icon = "🪝", name = "hook", category = "object" },
	{ icon = "🧰", name = "toolbox", category = "object" },
	{ icon = "🧲", name = "magnet", category = "object" },
	{ icon = "🪜", name = "ladder", category = "object" },
	{ icon = "⚗️", name = "alembic", category = "object" },
	{ icon = "🔬", name = "microscope", category = "object" },
	{ icon = "🔭", name = "telescope", category = "object" },
	{ icon = "📡", name = "satellite_antenna", category = "object" },
	{ icon = "💉", name = "syringe", category = "object" },
	{ icon = "💊", name = "pill", category = "object" },
	{ icon = "🚪", name = "door", category = "object" },
	{ icon = "🛗", name = "elevator", category = "object" },
	{ icon = "🪞", name = "mirror", category = "object" },
	{ icon = "🪟", name = "window", category = "object" },
	{ icon = "🛏️", name = "bed", category = "object" },
	{ icon = "🛋️", name = "couch_and_lamp", category = "object" },
	{ icon = "🪑", name = "chair", category = "object" },
	{ icon = "🚽", name = "toilet", category = "object" },
	{ icon = "🪠", name = "plunger", category = "object" },
	{ icon = "🚿", name = "shower", category = "object" },
	{ icon = "🛁", name = "bathtub", category = "object" },
	{ icon = "🪤", name = "mouse_trap", category = "object" },
	{ icon = "🪒", name = "razor", category = "object" },
	{ icon = "🧴", name = "lotion_bottle", category = "object" },
	{ icon = "🧷", name = "safety_pin", category = "object" },
	{ icon = "🧹", name = "broom", category = "object" },
	{ icon = "🧺", name = "basket", category = "object" },
	{ icon = "🧻", name = "roll_of_paper", category = "object" },
	{ icon = "🪣", name = "bucket", category = "object" },
	{ icon = "🧼", name = "soap", category = "object" },
	{ icon = "🪥", name = "toothbrush", category = "object" },
	{ icon = "🧽", name = "sponge", category = "object" },
	{ icon = "🧯", name = "fire_extinguisher", category = "object" },
	{ icon = "🛒", name = "shopping_cart", category = "object" },
	{ icon = "🎓", name = "graduation_cap", category = "object" },
	{ icon = "🎒", name = "school_backpack", category = "object" },
	{ icon = "👑", name = "crown", category = "object" },
	{ icon = "🎁", name = "wrapped_gift", category = "object" },
	{ icon = "🎀", name = "ribbon", category = "object" },
	{ icon = "🎗️", name = "reminder_ribbon", category = "object" },
	{ icon = "🎟️", name = "admission_tickets", category = "object" },
	{ icon = "🎫", name = "ticket", category = "object" },
	{ icon = "🏆", name = "trophy", category = "object" },
	{ icon = "⚽", name = "soccer_ball", category = "object" },
	{ icon = "🏀", name = "basketball", category = "object" },
	{ icon = "🏈", name = "american_football", category = "object" },
	{ icon = "⚾", name = "baseball", category = "object" },
	{ icon = "🥎", name = "softball", category = "object" },
	{ icon = "🎾", name = "tennis", category = "object" },
	{ icon = "🏐", name = "volleyball", category = "object" },
	{ icon = "🏉", name = "rugby_football", category = "object" },
	{ icon = "🥏", name = "flying_disc", category = "object" },
	{ icon = "🎱", name = "8_ball", category = "object" },
	{ icon = "🏓", name = "ping_pong", category = "object" },
	{ icon = "🏸", name = "badminton", category = "object" },
	{ icon = "🏒", name = "ice_hockey", category = "object" },
	{ icon = "🏑", name = "field_hockey", category = "object" },
	{ icon = "🥍", name = "lacrosse", category = "object" },
	{ icon = "🏏", name = "cricket_game", category = "object" },
	{ icon = "🥅", name = "goal_net", category = "object" },
	{ icon = "⛳", name = "flag_in_hole", category = "object" },
	{ icon = "⛸️", name = "ice_skate", category = "object" },
	{ icon = "🎿", name = "skis", category = "object" },
	{ icon = "🛷", name = "sled", category = "object" },
	{ icon = "🥌", name = "bowling", category = "object" },
	{ icon = "🎯", name = "direct_hit", category = "object" },
	{ icon = "🪁", name = "kite", category = "object" },
	{ icon = "🏹", name = "bow_and_arrow", category = "object" },
	{ icon = "🎣", name = "fishing_pole", category = "object" },
	{ icon = "🤿", name = "diving_mask", category = "object" },
	{ icon = "🥊", name = "boxing_glove", category = "object" },
	{ icon = "🥋", name = "martial_arts_uniform", category = "object" },
	{ icon = "🎽", name = "running_shirt", category = "object" },
	{ icon = "🎸", name = "guitar", category = "object" },
	{ icon = "🎷", name = "saxophone", category = "object" },
	{ icon = "🎺", name = "trumpet", category = "object" },
	{ icon = "🎹", name = "musical_keyboard", category = "object" },
	{ icon = "🎻", name = "violin", category = "object" },
	{ icon = "🥁", name = "drum", category = "object" },
	{ icon = "🪘", name = "long_drum", category = "object" },
	{ icon = "🎭", name = "performing_arts", category = "object" },
	{ icon = "🎨", name = "artist_palette", category = "object" },
	{ icon = "🎬", name = "clapper_board", category = "object" },
	{ icon = "🎤", name = "microphone", category = "object" },
	{ icon = "🎧", name = "headphone", category = "object" },
	{ icon = "🎚️", name = "level_slider", category = "object" },
	{ icon = "🎛️", name = "control_knobs", category = "object" },
	{ icon = "⏱️", name = "stopwatch", category = "object" },
	{ icon = "⏲️", name = "timer_clock", category = "object" },
	{ icon = "⏰", name = "alarm_clock", category = "object" },
	{ icon = "🕰️", name = "mantelpiece_clock", category = "object" },
	{ icon = "⌛", name = "hourglass", category = "object" },
	{ icon = "⏳", name = "hourglass_flowing_sand", category = "object" },
	{ icon = "📱", name = "mobile_phone", category = "object" },
	{ icon = "📲", name = "calling_mobile_phone", category = "object" },
	{ icon = "💻", name = "laptop", category = "object" },
	{ icon = "⌨️", name = "keyboard", category = "object" },
	{ icon = "🖥️", name = "desktop_computer", category = "object" },
	{ icon = "🖨️", name = "printer", category = "object" },
	{ icon = "🖱️", name = "computer_mouse", category = "object" },
	{ icon = "🖲️", name = "trackball", category = "object" },
	{ icon = "💽", name = "computer_disk", category = "object" },
	{ icon = "💾", name = "floppy_disk", category = "object" },
	{ icon = "💿", name = "optical_disk", category = "object" },
	{ icon = "📀", name = "dvd", category = "object" },
	{ icon = "🧮", name = "abacus", category = "object" },
	{ icon = "🎥", name = "movie_camera", category = "object" },
	{ icon = "🎞️", name = "film_frames", category = "object" },
	{ icon = "📽️", name = "film_projector", category = "object" },
	{ icon = "🎬", name = "clapper_board", category = "object" },
	{ icon = "📺", name = "television", category = "object" },
	{ icon = "📷", name = "camera", category = "object" },
	{ icon = "📸", name = "camera_with_flash", category = "object" },
	{ icon = "📹", name = "video_camera", category = "object" },
	{ icon = "📼", name = "videocassette", category = "object" },
	{ icon = "🔍", name = "magnifying_glass_tilted_left", category = "object" },
	{ icon = "🔎", name = "magnifying_glass_tilted_right", category = "object" },
	{ icon = "🕯️", name = "candle", category = "object" },
	{ icon = "💡", name = "light_bulb", category = "object" },
	{ icon = "🔦", name = "flashlight", category = "object" },
	{ icon = "🏮", name = "red_paper_lantern", category = "object" },
	{ icon = "🏯", name = "japanese_castle", category = "object" },
	{ icon = "🏰", name = "european_castle", category = "object" },
	{ icon = "💒", name = "wedding", category = "object" },
	{ icon = "🗼", name = "tokyo_tower", category = "object" },
	{ icon = "🗽", name = "statue_of_liberty", category = "object" },
	{ icon = "🌁", name = "foggy", category = "nature" },
	{ icon = "🌂", name = "closed_umbrella", category = "nature" },
	{ icon = "🌄", name = "sunrise_over_mountains", category = "nature" },
	{ icon = "🌅", name = "sunrise", category = "nature" },
	{ icon = "🌆", name = "cityscape_at_dusk", category = "nature" },
	{ icon = "🌇", name = "sunset", category = "nature" },
	{ icon = "🌉", name = "bridge_at_night", category = "nature" },
	{ icon = "🌌", name = "milky_way", category = "nature" },
	{ icon = "🌍", name = "earth_africa", category = "nature" },
	{ icon = "🌎", name = "earth_americas", category = "nature" },
	{ icon = "🌏", name = "earth_asia", category = "nature" },
	{ icon = "🌐", name = "globe_with_meridians", category = "nature" },
	{ icon = "🗺️", name = "world_map", category = "nature" },
	{ icon = "🗿", name = "moai", category = "nature" },
	{ icon = "⛲", name = "fountain", category = "nature" },
	{ icon = "⛱️", name = "umbrella_on_ground", category = "nature" },
	{ icon = "🌋", name = "volcano", category = "nature" },
	{ icon = "🌊", name = "water_wave", category = "nature" },
	{ icon = "🌌", name = "milky_way", category = "nature" },
	{ icon = "🌍", name = "earth_africa", category = "nature" },
	{ icon = "🌎", name = "earth_americas", category = "nature" },
	{ icon = "🌏", name = "earth_asia", category = "nature" },
	{ icon = "🌑", name = "new_moon", category = "nature" },
	{ icon = "🌒", name = "waxing_crescent_moon", category = "nature" },
	{ icon = "🌓", name = "first_quarter_moon", category = "nature" },
	{ icon = "🌔", name = "waxing_gibbous_moon", category = "nature" },
	{ icon = "🌕", name = "full_moon", category = "nature" },
	{ icon = "🌖", name = "waning_gibbous_moon", category = "nature" },
	{ icon = "🌗", name = "last_quarter_moon", category = "nature" },
	{ icon = "🌘", name = "waning_crescent_moon", category = "nature" },
	{ icon = "🌙", name = "crescent_moon", category = "nature" },
	{ icon = "🌚", name = "new_moon_face", category = "nature" },
	{ icon = "🌛", name = "first_quarter_moon_face", category = "nature" },
	{ icon = "🌜", name = "last_quarter_moon_face", category = "nature" },
	{ icon = "☀️", name = "sun", category = "nature" },
	{ icon = "🌝", name = "full_moon_face", category = "nature" },
	{ icon = "🌞", name = "sun_with_face", category = "nature" },
	{ icon = "⭐", name = "star", category = "nature" },
	{ icon = "🌟", name = "glowing_star", category = "nature" },
	{ icon = "🌠", name = "shooting_star", category = "nature" },
	{ icon = "🌌", name = "milky_way", category = "nature" },
	{ icon = "☁️", name = "cloud", category = "nature" },
	{ icon = "🌥️", name = "sun_behind_large_cloud", category = "nature" },
	{ icon = "🌦️", name = "sun_behind_rain_cloud", category = "nature" },
	{ icon = "🌧️", name = "cloud_with_rain", category = "nature" },
	{ icon = "⛈️", name = "cloud_with_lightning_and_rain", category = "nature" },
	{ icon = "🌩️", name = "cloud_with_lightning", category = "nature" },
	{ icon = "🌨️", name = "cloud_with_snow", category = "nature" },
	{ icon = "🌪️", name = "tornado", category = "nature" },
	{ icon = "🌫️", name = "fog", category = "nature" },
	{ icon = "🌬️", name = "wind_face", category = "nature" },
	{ icon = "🌈", name = "rainbow", category = "nature" },
	{ icon = "🌂", name = "closed_umbrella", category = "nature" },
	{ icon = "☂️", name = "umbrella", category = "nature" },
	{ icon = "☔", name = "umbrella_with_rain_drops", category = "nature" },
	{ icon = "💧", name = "droplet", category = "nature" },
	{ icon = "💦", name = "sweat_droplets", category = "nature" },
	{ icon = "🌊", name = "water_wave", category = "nature" },
	{ icon = "🍏", name = "green_apple", category = "food" },
	{ icon = "🍎", name = "red_apple", category = "food" },
	{ icon = "🍐", name = "pear", category = "food" },
	{ icon = "🍊", name = "tangerine", category = "food" },
	{ icon = "🍋", name = "lemon", category = "food" },
	{ icon = "🍌", name = "banana", category = "food" },
	{ icon = "🍉", name = "watermelon", category = "food" },
	{ icon = "🍇", name = "grapes", category = "food" },
	{ icon = "🍓", name = "strawberry", category = "food" },
	{ icon = "🫐", name = "blueberries", category = "food" },
	{ icon = "🍈", name = "melon", category = "food" },
	{ icon = "🍒", name = "cherries", category = "food" },
	{ icon = "🍑", name = "peach", category = "food" },
	{ icon = "🥭", name = "mango", category = "food" },
	{ icon = "🍍", name = "pineapple", category = "food" },
	{ icon = "🥥", name = "coconut", category = "food" },
	{ icon = "🥝", name = "kiwi_fruit", category = "food" },
	{ icon = "🍅", name = "tomato", category = "food" },
	{ icon = "🍆", name = "eggplant", category = "food" },
	{ icon = "🥑", name = "avocado", category = "food" },
	{ icon = "🥦", name = "broccoli", category = "food" },
	{ icon = "🥬", name = "leafy_green", category = "food" },
	{ icon = "🥒", name = "cucumber", category = "food" },
	{ icon = "🌶️", name = "hot_pepper", category = "food" },
	{ icon = "🫑", name = "bell_pepper", category = "food" },
	{ icon = "🌽", name = "ear_of_corn", category = "food" },
	{ icon = "🥕", name = "carrot", category = "food" },
	{ icon = "🧄", name = "garlic", category = "food" },
	{ icon = "🧅", name = "onion", category = "food" },
	{ icon = "🥔", name = "potato", category = "food" },
	{ icon = "🍞", name = "bread", category = "food" },
	{ icon = "🥐", name = "croissant", category = "food" },
	{ icon = "🥖", name = "baguette_bread", category = "food" },
	{ icon = "🥨", name = "pretzel", category = "food" },
	{ icon = "🥯", name = "bagel", category = "food" },
	{ icon = "🥞", name = "pancakes", category = "food" },
	{ icon = "🧇", name = "waffle", category = "food" },
	{ icon = "🧀", name = "cheese_wedge", category = "food" },
	{ icon = "🍖", name = "meat_on_bone", category = "food" },
	{ icon = "🍗", name = "poultry_leg", category = "food" },
	{ icon = "🥩", name = "cut_of_meat", category = "food" },
	{ icon = "🥓", name = "bacon", category = "food" },
	{ icon = "🍔", name = "hamburger", category = "food" },
	{ icon = "🍟", name = "french_fries", category = "food" },
	{ icon = "🍕", name = "pizza", category = "food" },
	{ icon = "🌭", name = "hot_dog", category = "food" },
	{ icon = "🥪", name = "sandwich", category = "food" },
	{ icon = "🌮", name = "taco", category = "food" },
	{ icon = "🌯", name = "burrito", category = "food" },
	{ icon = "🫔", name = "tamale", category = "food" },
	{ icon = "🥙", name = "stuffed_flatbread", category = "food" },
	{ icon = "🧆", name = "falafel", category = "food" },
	{ icon = "🥚", name = "egg", category = "food" },
	{ icon = "🍳", name = "cooking", category = "food" },
	{ icon = "🥘", name = "shallow_pan_of_food", category = "food" },
	{ icon = "🍲", name = "pot_of_food", category = "food" },
	{ icon = "🫕", name = "fondue", category = "food" },
	{ icon = "🥣", name = "bowl_with_spoon", category = "food" },
	{ icon = "🥗", name = "green_salad", category = "food" },
	{ icon = "🍿", name = "popcorn", category = "food" },
	{ icon = "🧈", name = "butter", category = "food" },
	{ icon = "🧂", name = "salt", category = "food" },
	{ icon = "🥫", name = "curry_rice", category = "food" },
	{ icon = "🍱", name = "bento", category = "food" },
	{ icon = "🍘", name = "rice_cracker", category = "food" },
	{ icon = "🍙", name = "rice_ball", category = "food" },
	{ icon = "🍚", name = "cooked_rice", category = "food" },
	{ icon = "🍛", name = "curry_rice", category = "food" },
	{ icon = "🍜", name = "steaming_bowl", category = "food" },
	{ icon = "🍝", name = "spaghetti", category = "food" },
	{ icon = "🍠", name = "roasted_sweet_potato", category = "food" },
	{ icon = "🍢", name = "oden", category = "food" },
	{ icon = "🍣", name = "sushi", category = "food" },
	{ icon = "🍤", name = "fried_shrimp", category = "food" },
	{ icon = "🍥", name = "fish_cake_with_swirl", category = "food" },
	{ icon = "🥟", name = "dumpling", category = "food" },
	{ icon = "🦪", name = "oyster", category = "food" },
	{ icon = "🍡", name = "dango", category = "food" },
	{ icon = "🥠", name = "fortune_cookie", category = "food" },
	{ icon = "🥡", name = "takeout_box", category = "food" },
	{ icon = "🍦", name = "soft_ice_cream", category = "food" },
	{ icon = "🍧", name = "shaved_ice", category = "food" },
	{ icon = "🍨", name = "ice_cream", category = "food" },
	{ icon = "🍩", name = "doughnut", category = "food" },
	{ icon = "🍪", name = "cookie", category = "food" },
	{ icon = "🎂", name = "birthday_cake", category = "food" },
	{ icon = "🍰", name = "shortcake", category = "food" },
	{ icon = "🧁", name = "cupcake", category = "food" },
	{ icon = "🥧", name = "pie", category = "food" },
	{ icon = "🍫", name = "chocolate_bar", category = "food" },
	{ icon = "🍬", name = "candy", category = "food" },
	{ icon = "🍭", name = "lollipop", category = "food" },
	{ icon = "🍮", name = "custard", category = "food" },
	{ icon = "🍯", name = "honey_pot", category = "food" },
	{ icon = "🥛", name = "glass_of_milk", category = "food" },
	{ icon = "🍼", name = "baby_bottle", category = "food" },
	{ icon = "☕", name = "hot_beverage", category = "food" },
	{ icon = "🫖", name = "teapot", category = "food" },
	{ icon = "🍵", name = "teacup_without_handle", category = "food" },
	{ icon = "🍶", name = "sake", category = "food" },
	{ icon = "🍺", name = "beer_mug", category = "food" },
	{ icon = "🍻", name = "clinking_beer_mugs", category = "food" },
	{ icon = "🥂", name = "clinking_glasses", category = "food" },
	{ icon = "🍷", name = "wine_glass", category = "food" },
	{ icon = "🥃", name = "tumbler_glass", category = "food" },
	{ icon = "🍸", name = "cocktail_glass", category = "food" },
	{ icon = "🍹", name = "tropical_drink", category = "food" },
	{ icon = "🍾", name = "bottle_with_popping_cork", category = "food" },
	{ icon = "🧊", name = "ice", category = "food" },
	{ icon = "🥄", name = "spoon", category = "food" },
	{ icon = "🍴", name = "fork_and_knife", category = "food" },
	{ icon = "🍽️", name = "fork_and_knife_with_plate", category = "food" },
	{ icon = "🥣", name = "bowl_with_spoon", category = "food" },
	{ icon = "🥗", name = "green_salad", category = "food" },
	{ icon = "🥘", name = "shallow_pan_of_food", category = "food" },
	{ icon = "🫓", name = "flatbread", category = "food" },
	{ icon = "🧆", name = "falafel", category = "food" },
	{ icon = "🥚", name = "egg", category = "food" },
	{ icon = "🍳", name = "cooking", category = "food" },
	{ icon = "🥮", name = "moon_cake", category = "food" },
	{ icon = "🍥", name = "fish_cake_with_swirl", category = "food" },
	{ icon = "🥟", name = "dumpling", category = "food" },
	{ icon = "🦪", name = "oyster", category = "food" },
	{ icon = "🍡", name = "dango", category = "food" },
	{ icon = "🥠", name = "fortune_cookie", category = "food" },
	{ icon = "🥡", name = "takeout_box", category = "food" },
	{ icon = "🚗", name = "automobile", category = "travel" },
	{ icon = "🚕", name = "taxi", category = "travel" },
	{ icon = "🚙", name = "sport_utility_vehicle", category = "travel" },
	{ icon = "🚌", name = "bus", category = "travel" },
	{ icon = "🚎", name = "trolleybus", category = "travel" },
	{ icon = "🏎️", name = "racing_car", category = "travel" },
	{ icon = "🚓", name = "police_car", category = "travel" },
	{ icon = "🚑", name = "ambulance", category = "travel" },
	{ icon = "🚒", name = "fire_engine", category = "travel" },
	{ icon = "🚐", name = "minibus", category = "travel" },
	{ icon = "🛻", name = "pickup_truck", category = "travel" },
	{ icon = "🚚", name = "delivery_truck", category = "travel" },
	{ icon = "🚛", name = "articulated_lorry", category = "travel" },
	{ icon = "🚜", name = "tractor", category = "travel" },
	{ icon = "🏍️", name = "motorcycle", category = "travel" },
	{ icon = "🛵", name = "motor_scooter", category = "travel" },
	{ icon = "🚲", name = "bicycle", category = "travel" },
	{ icon = "🛴", name = "kick_scooter", category = "travel" },
	{ icon = "🚏", name = "bus_stop", category = "travel" },
	{ icon = "🛣️", name = "motorway", category = "travel" },
	{ icon = "🛤️", name = "railway_track", category = "travel" },
	{ icon = "⛽", name = "fuel_pump", category = "travel" },
	{ icon = "🚨", name = "police_car_light", category = "travel" },
	{ icon = "🚥", name = "horizontal_traffic_light", category = "travel" },
	{ icon = "🚦", name = "vertical_traffic_light", category = "travel" },
	{ icon = "🛑", name = "stop_sign", category = "travel" },
	{ icon = "🚧", name = "construction", category = "travel" },
	{ icon = "⚓", name = "anchor", category = "travel" },
	{ icon = "⛵", name = "sailboat", category = "travel" },
	{ icon = "🚤", name = "speedboat", category = "travel" },
	{ icon = "🛳️", name = "passenger_ship", category = "travel" },
	{ icon = "⛴️", name = "ferry", category = "travel" },
	{ icon = "🛥️", name = "motor_boat", category = "travel" },
	{ icon = "🚢", name = "ship", category = "travel" },
	{ icon = "✈️", name = "airplane", category = "travel" },
	{ icon = "🛩️", name = "small_airplane", category = "travel" },
	{ icon = "🛫", name = "airplane_departure", category = "travel" },
	{ icon = "🛬", name = "airplane_arrival", category = "travel" },
	{ icon = "🪂", name = "parachute", category = "travel" },
	{ icon = "💺", name = "seat", category = "travel" },
	{ icon = "🚁", name = "helicopter", category = "travel" },
	{ icon = "🚟", name = "suspension_railway", category = "travel" },
	{ icon = "🚠", name = "mountain_cableway", category = "travel" },
	{ icon = "🚡", name = "aerial_tramway", category = "travel" },
	{ icon = "🚀", name = "rocket", category = "travel" },
	{ icon = "🛸", name = "flying_saucer", category = "travel" },
	{ icon = "🏠", name = "house", category = "travel" },
	{ icon = "🏡", name = "house_with_garden", category = "travel" },
	{ icon = "🏢", name = "office_building", category = "travel" },
	{ icon = "🏣", name = "japanese_post_office", category = "travel" },
	{ icon = "🏤", name = "post_office", category = "travel" },
	{ icon = "🏥", name = "hospital", category = "travel" },
	{ icon = "🏦", name = "bank", category = "travel" },
	{ icon = "🏨", name = "hotel", category = "travel" },
	{ icon = "🏩", name = "love_hotel", category = "travel" },
	{ icon = "🏪", name = "convenience_store", category = "travel" },
	{ icon = "🏫", name = "school", category = "travel" },
	{ icon = "🏬", name = "department_store", category = "travel" },
	{ icon = "🏭", name = "factory", category = "travel" },
	{ icon = "🏯", name = "japanese_castle", category = "travel" },
	{ icon = "🏰", name = "european_castle", category = "travel" },
	{ icon = "💒", name = "wedding", category = "travel" },
	{ icon = "🗼", name = "tokyo_tower", category = "travel" },
	{ icon = "🗽", name = "statue_of_liberty", category = "travel" },
	{ icon = "⛪", name = "church", category = "travel" },
	{ icon = "🕌", name = "mosque", category = "travel" },
	{ icon = "🛕", name = "hindu_temple", category = "travel" },
	{ icon = "🕍", name = "synagogue", category = "travel" },
	{ icon = "⛩️", name = "shinto_shrine", category = "travel" },
	{ icon = "🕋", name = "kaaba", category = "travel" },
	{ icon = "⛲", name = "fountain", category = "travel" },
	{ icon = "⛺", name = "tent", category = "travel" },
	{ icon = "🌁", name = "foggy", category = "travel" },
	{ icon = "🌃", name = "night_with_stars", category = "travel" },
	{ icon = "🏙️", name = "cityscape", category = "travel" },
	{ icon = "🌄", name = "sunrise_over_mountains", category = "travel" },
	{ icon = "🌅", name = "sunrise", category = "travel" },
	{ icon = "🌆", name = "cityscape_at_dusk", category = "travel" },
	{ icon = "🌇", name = "sunset", category = "travel" },
	{ icon = "🌉", name = "bridge_at_night", category = "travel" },
	{ icon = "♨️", name = "hot_springs", category = "travel" },
	{ icon = "🎠", name = "carousel_horse", category = "travel" },
	{ icon = "🎡", name = "ferris_wheel", category = "travel" },
	{ icon = "🎢", name = "roller_coaster", category = "travel" },
	{ icon = "🚂", name = "locomotive", category = "travel" },
	{ icon = "🚃", name = "railway_car", category = "travel" },
	{ icon = "🚄", name = "high_speed_train", category = "travel" },
	{ icon = "🚅", name = "bullet_train", category = "travel" },
	{ icon = "🚆", name = "train", category = "travel" },
	{ icon = "🚇", name = "metro", category = "travel" },
	{ icon = "🚈", name = "light_rail", category = "travel" },
	{ icon = "🚉", name = "station", category = "travel" },
	{ icon = "🚊", name = "tram", category = "travel" },
	{ icon = "🚝", name = "monorail", category = "travel" },
	{ icon = "🚞", name = "mountain_railway", category = "travel" },
	{ icon = "🚋", name = "tram_car", category = "travel" },
	{ icon = "🚍", name = "oncoming_bus", category = "travel" },
	{ icon = "🚔", name = "oncoming_police_car", category = "travel" },
	{ icon = "🚘", name = "oncoming_automobile", category = "travel" },
	{ icon = "🚖", name = "oncoming_taxi", category = "travel" },
	{ icon = "🚡", name = "aerial_tramway", category = "travel" },
	{ icon = "🚠", name = "mountain_cableway", category = "travel" },
	{ icon = "🚟", name = "suspension_railway", category = "travel" },
	{ icon = "🚃", name = "railway_car", category = "travel" },
	{ icon = "🚋", name = "tram_car", category = "travel" },
	{ icon = "🚎", name = "trolleybus", category = "travel" },
	{ icon = "🚐", name = "minibus", category = "travel" },
	{ icon = "🚑", name = "ambulance", category = "travel" },
	{ icon = "🚒", name = "fire_engine", category = "travel" },
	{ icon = "🚓", name = "police_car", category = "travel" },
	{ icon = "🚕", name = "taxi", category = "travel" },
	{ icon = "🚗", name = "automobile", category = "travel" },
	{ icon = "🚙", name = "sport_utility_vehicle", category = "travel" },
	{ icon = "🚌", name = "bus", category = "travel" },
	{ icon = "🚍", name = "oncoming_bus", category = "travel" },
	{ icon = "🚔", name = "oncoming_police_car", category = "travel" },
	{ icon = "🚘", name = "oncoming_automobile", category = "travel" },
	{ icon = "🚖", name = "oncoming_taxi", category = "travel" },
	{ icon = "🏎️", name = "racing_car", category = "travel" },
	{ icon = "🚛", name = "articulated_lorry", category = "travel" },
	{ icon = "🚚", name = "delivery_truck", category = "travel" },
	{ icon = "🚜", name = "tractor", category = "travel" },
	{ icon = "🛑", name = "stop_sign", category = "travel" },
	{ icon = "🚧", name = "construction", category = "travel" },
	{ icon = "🚦", name = "vertical_traffic_light", category = "travel" },
	{ icon = "🚥", name = "horizontal_traffic_light", category = "travel" },
	{ icon = "🗿", name = "moai", category = "travel" },
	{ icon = "🗽", name = "statue_of_liberty", category = "travel" },
	{ icon = "🗼", name = "tokyo_tower", category = "travel" },
	{ icon = "🗻", name = "mount_fuji", category = "travel" },
	{ icon = "🏕️", name = "camping", category = "travel" },
	{ icon = "🏖️", name = "beach_with_umbrella", category = "travel" },
	{ icon = "🏜️", name = "desert", category = "travel" },
	{ icon = "🏝️", name = "desert_island", category = "travel" },
	{ icon = "🏞️", name = "national_park", category = "travel" },
	{ icon = "🏟️", name = "stadium", category = "travel" },
	{ icon = "🏛️", name = "classical_building", category = "travel" },
	{ icon = "🏗️", name = "building_construction", category = "travel" },
	{ icon = "🧱", name = "brick", category = "travel" },
	{ icon = "🪨", name = "rock", category = "travel" },
	{ icon = "🪵", name = "wood", category = "travel" },
	{ icon = "🛖", name = "hut", category = "travel" },
	{ icon = "🧿", name = "nazar_amulet", category = "travel" },
	{ icon = "🗿", name = "moai", category = "travel" },
	{ icon = "🎰", name = "slot_machine", category = "travel" },
	{ icon = "🎱", name = "8_ball", category = "travel" },
	{ icon = "🔮", name = "crystal_ball", category = "travel" },
	{ icon = "🧩", name = "puzzle_piece", category = "travel" },
	{ icon = "🧸", name = "teddy_bear", category = "travel" },
	{ icon = "♠️", name = "spade_suit", category = "symbol" },
	{ icon = "♣️", name = "club_suit", category = "symbol" },
	{ icon = "♥️", name = "heart_suit", category = "symbol" },
	{ icon = "♦️", name = "diamond_suit", category = "symbol" },
	{ icon = "🎴", name = "flower_playing_cards", category = "symbol" },
	{ icon = "🎭", name = "performing_arts", category = "symbol" },
	{ icon = "🖼️", name = "frame_with_picture", category = "symbol" },
	{ icon = "🎨", name = "artist_palette", category = "symbol" },
	{ icon = "🧵", name = "thread", category = "symbol" },
	{ icon = "🪡", name = "sewing_needle", category = "symbol" },
	{ icon = "🧶", name = "yarn", category = "symbol" },
	{ icon = "🪢", name = "knot", category = "symbol" },
	{ icon = "🇺🇸", name = "flag_usa", category = "flag" },
	{ icon = "🇬🇧", name = "flag_uk", category = "flag" },
	{ icon = "🇨🇦", name = "flag_canada", category = "flag" },
	{ icon = "🇦🇺", name = "flag_australia", category = "flag" },
	{ icon = "🇩🇪", name = "flag_germany", category = "flag" },
	{ icon = "🇫🇷", name = "flag_france", category = "flag" },
	{ icon = "🇮🇹", name = "flag_italy", category = "flag" },
	{ icon = "🇪🇸", name = "flag_spain", category = "flag" },
	{ icon = "🇯🇵", name = "flag_japan", category = "flag" },
	{ icon = "🇰🇷", name = "flag_south_korea", category = "flag" },
	{ icon = "🇨🇳", name = "flag_china", category = "flag" },
	{ icon = "🇮🇳", name = "flag_india", category = "flag" },
	{ icon = "🇧🇷", name = "flag_brazil", category = "flag" },
	{ icon = "🇲🇽", name = "flag_mexico", category = "flag" },
	{ icon = "🇷🇺", name = "flag_russia", category = "flag" },
	{ icon = "✅", name = "check_mark", category = "symbol" },
	{ icon = "❌", name = "cross_mark", category = "symbol" },
	{ icon = "❓", name = "question_mark", category = "symbol" },
	{ icon = "❗", name = "exclamation_mark", category = "symbol" },
	{ icon = "💯", name = "hundred_points", category = "symbol" },
	{ icon = "🔴", name = "red_circle", category = "symbol" },
	{ icon = "🟠", name = "orange_circle", category = "symbol" },
	{ icon = "🟡", name = "yellow_circle", category = "symbol" },
	{ icon = "🟢", name = "green_circle", category = "symbol" },
	{ icon = "🔵", name = "blue_circle", category = "symbol" },
	{ icon = "🟣", name = "purple_circle", category = "symbol" },
	{ icon = "⚫", name = "black_circle", category = "symbol" },
	{ icon = "⚪", name = "white_circle", category = "symbol" },
	{ icon = "🟤", name = "brown_circle", category = "symbol" },
	{ icon = "🔺", name = "red_triangle_pointed_up", category = "symbol" },
	{ icon = "🔻", name = "red_triangle_pointed_down", category = "symbol" },
	{ icon = "🔸", name = "small_orange_diamond", category = "symbol" },
	{ icon = "🔹", name = "small_blue_diamond", category = "symbol" },
	{ icon = "🔶", name = "large_orange_diamond", category = "symbol" },
	{ icon = "🔷", name = "large_blue_diamond", category = "symbol" },
	{ icon = "🔳", name = "white_square_button", category = "symbol" },
	{ icon = "🔲", name = "black_square_button", category = "symbol" },
	{ icon = "▪️", name = "black_small_square", category = "symbol" },
	{ icon = "▫️", name = "white_small_square", category = "symbol" },
	{ icon = "◾", name = "black_medium_square", category = "symbol" },
	{ icon = "◽", name = "white_medium_square", category = "symbol" },
	{ icon = "◼️", name = "black_medium_square", category = "symbol" },
	{ icon = "◻️", name = "white_medium_square", category = "symbol" },
	{ icon = "⬛", name = "black_large_square", category = "symbol" },
	{ icon = "⬜", name = "white_large_square", category = "symbol" },
	{ icon = "🟥", name = "red_square", category = "symbol" },
	{ icon = "🟧", name = "orange_square", category = "symbol" },
	{ icon = "🟨", name = "yellow_square", category = "symbol" },
	{ icon = "🟩", name = "green_square", category = "symbol" },
	{ icon = "🟦", name = "blue_square", category = "symbol" },
	{ icon = "🟪", name = "purple_square", category = "symbol" },
	{ icon = "🟫", name = "brown_square", category = "symbol" },
	{ icon = "⬅️", name = "left_arrow", category = "symbol" },
	{ icon = "➡️", name = "right_arrow", category = "symbol" },
	{ icon = "⬆️", name = "up_arrow", category = "symbol" },
	{ icon = "⬇️", name = "down_arrow", category = "symbol" },
	{ icon = "↗️", name = "up_right_arrow", category = "symbol" },
	{ icon = "↘️", name = "down_right_arrow", category = "symbol" },
	{ icon = "↙️", name = "down_left_arrow", category = "symbol" },
	{ icon = "↖️", name = "up_left_arrow", category = "symbol" },
	{ icon = "↕️", name = "up_down_arrow", category = "symbol" },
	{ icon = "↔️", name = "left_right_arrow", category = "symbol" },
	{ icon = "🔄", name = "counterclockwise_arrows_button", category = "symbol" },
	{ icon = "🔙", name = "back_arrow", category = "symbol" },
	{ icon = "🔚", name = "end_arrow", category = "symbol" },
	{ icon = "🔛", name = "on_arrow", category = "symbol" },
	{ icon = "🔜", name = "soon_arrow", category = "symbol" },
	{ icon = "🔝", name = "top_arrow", category = "symbol" },
	{ icon = "🆚", name = "vs_button", category = "symbol" },
	{ icon = "💮", name = "white_flower", category = "symbol" },
	{ icon = "🆕", name = "new_button", category = "symbol" },
	{ icon = "🆓", name = "free_button", category = "symbol" },
	{ icon = "🆖", name = "ng_button", category = "symbol" },
	{ icon = "🆗", name = "cool_button", category = "symbol" },
	{ icon = "🆙", name = "up_button", category = "symbol" },
	{ icon = "🆒", name = "cool_button", category = "symbol" },
	{ icon = "🆓", name = "free_button", category = "symbol" },
	{ icon = "0️⃣", name = "keycap_0", category = "symbol" },
	{ icon = "1️⃣", name = "keycap_1", category = "symbol" },
	{ icon = "2️⃣", name = "keycap_2", category = "symbol" },
	{ icon = "3️⃣", name = "keycap_3", category = "symbol" },
	{ icon = "4️⃣", name = "keycap_4", category = "symbol" },
	{ icon = "5️⃣", name = "keycap_5", category = "symbol" },
	{ icon = "6️⃣", name = "keycap_6", category = "symbol" },
	{ icon = "7️⃣", name = "keycap_7", category = "symbol" },
	{ icon = "8️⃣", name = "keycap_8", category = "symbol" },
	{ icon = "9️⃣", name = "keycap_9", category = "symbol" },
	{ icon = "🔟", name = "keycap_10", category = "symbol" },
	{ icon = "🔒", name = "locked", category = "symbol" },
	{ icon = "🔓", name = "unlocked", category = "symbol" },
	{ icon = "🔏", name = "locked_with_pen", category = "symbol" },
	{ icon = "🔐", name = "locked_with_key", category = "symbol" },
	{ icon = "🔑", name = "key", category = "symbol" },
	{ icon = "🗝️", name = "old_key", category = "symbol" },
	{ icon = "🔔", name = "bell", category = "symbol" },
	{ icon = "🔕", name = "bell_with_slash", category = "symbol" },
	{ icon = "🔇", name = "muted_speaker", category = "symbol" },
	{ icon = "🔈", name = "speaker_low_volume", category = "symbol" },
	{ icon = "🔉", name = "speaker_medium_volume", category = "symbol" },
	{ icon = "🔊", name = "speaker_high_volume", category = "symbol" },
	{ icon = "📢", name = "loudspeaker", category = "symbol" },
	{ icon = "📣", name = "megaphone", category = "symbol" },
	{ icon = "🔍", name = "magnifying_glass_tilted_left", category = "symbol" },
	{ icon = "🔎", name = "magnifying_glass_tilted_right", category = "symbol" },
	{ icon = "🔬", name = "microscope", category = "symbol" },
	{ icon = "🔭", name = "telescope", category = "symbol" },
	{ icon = "📡", name = "satellite_antenna", category = "symbol" },
	{ icon = "📧", name = "e_mail", category = "symbol" },
	{ icon = "📨", name = "incoming_envelope", category = "symbol" },
	{ icon = "📩", name = "envelope_with_arrow", category = "symbol" },
	{ icon = "📤", name = "outbox_tray", category = "symbol" },
	{ icon = "📥", name = "inbox_tray", category = "symbol" },
	{ icon = "📦", name = "package", category = "symbol" },
	{ icon = "📫", name = "closed_mailbox_with_raised_flag", category = "symbol" },
	{ icon = "📪", name = "closed_mailbox_with_lowered_flag", category = "symbol" },
	{ icon = "📬", name = "open_mailbox_with_raised_flag", category = "symbol" },
	{ icon = "📭", name = "open_mailbox_with_lowered_flag", category = "symbol" },
	{ icon = "📮", name = "postbox", category = "symbol" },
	{ icon = "🗳️", name = "ballot_box_with_ballot", category = "symbol" },
	{ icon = "✏️", name = "pencil", category = "symbol" },
	{ icon = "✒️", name = "black_nib", category = "symbol" },
	{ icon = "🖋️", name = "fountain_pen", category = "symbol" },
	{ icon = "🖊️", name = "pen", category = "symbol" },
	{ icon = "🖌️", name = "paintbrush", category = "symbol" },
	{ icon = "🖍️", name = "crayon", category = "symbol" },
	{ icon = "📝", name = "memo", category = "symbol" },
	{ icon = "💼", name = "briefcase", category = "symbol" },
	{ icon = "📁", name = "file_folder", category = "symbol" },
	{ icon = "📂", name = "open_file_folder", category = "symbol" },
	{ icon = "🗂️", name = "card_index_dividers", category = "symbol" },
	{ icon = "📅", name = "calendar", category = "symbol" },
	{ icon = "📆", name = "tear_off_calendar", category = "symbol" },
	{ icon = "🗒️", name = "spiral_notepad", category = "symbol" },
	{ icon = "🗓️", name = "spiral_calendar", category = "symbol" },
	{ icon = "📇", name = "card_index", category = "symbol" },
	{ icon = "📈", name = "chart_increasing", category = "symbol" },
	{ icon = "📉", name = "chart_decreasing", category = "symbol" },
	{ icon = "📊", name = "bar_chart", category = "symbol" },
	{ icon = "📋", name = "clipboard", category = "symbol" },
	{ icon = "📌", name = "pushpin", category = "symbol" },
	{ icon = "📍", name = "round_pushpin", category = "symbol" },
	{ icon = "📎", name = "paperclip", category = "symbol" },
	{ icon = "🖇️", name = "linked_paperclips", category = "symbol" },
	{ icon = "📏", name = "straight_ruler", category = "symbol" },
	{ icon = "📐", name = "triangular_ruler", category = "symbol" },
	{ icon = "✂️", name = "scissors", category = "symbol" },
	{ icon = "🗃️", name = "card_file_box", category = "symbol" },
	{ icon = "🗄️", name = "file_cabinet", category = "symbol" },
	{ icon = "🗑️", name = "wastebasket", category = "symbol" },
	{ icon = "🔒", name = "locked", category = "symbol" },
	{ icon = "🔓", name = "unlocked", category = "symbol" },
	{ icon = "🔏", name = "locked_with_pen", category = "symbol" },
	{ icon = "🔐", name = "locked_with_key", category = "symbol" },
	{ icon = "🔑", name = "key", category = "symbol" },
	{ icon = "🗝️", name = "old_key", category = "symbol" },
	{ icon = "🔨", name = "hammer", category = "tool" },
	{ icon = "🪓", name = "axe", category = "tool" },
	{ icon = "⛏️", name = "pick", category = "tool" },
	{ icon = "⚒️", name = "hammer_and_pick", category = "tool" },
	{ icon = "🛠️", name = "hammer_and_wrench", category = "tool" },
	{ icon = "🗡️", name = "dagger", category = "tool" },
	{ icon = "⚔️", name = "crossed_swords", category = "tool" },
	{ icon = "🔫", name = "water_pistol", category = "tool" },
	{ icon = "🏹", name = "bow_and_arrow", category = "tool" },
	{ icon = "🛡️", name = "shield", category = "tool" },
	{ icon = "🔧", name = "wrench", category = "tool" },
	{ icon = "🔨", name = "hammer", category = "tool" },
	{ icon = "⚙️", name = "gear", category = "tool" },
	{ icon = "🗜️", name = "clamp", category = "tool" },
	{ icon = "⚖️", name = "balance_scale", category = "tool" },
	{ icon = "🦯", name = "white_cane", category = "tool" },
	{ icon = "⛓️", name = "chains", category = "tool" },
	{ icon = "🧰", name = "toolbox", category = "tool" },
	{ icon = "🧲", name = "magnet", category = "tool" },
	{ icon = "🪛", name = "screwdriver", category = "tool" },
	{ icon = "🪚", name = "saw", category = "tool" },
	{ icon = "🔩", name = "nut_and_bolt", category = "tool" },
	{ icon = "⚗️", name = "alembic", category = "tool" },
	{ icon = "🧪", name = "test_tube", category = "tool" },
	{ icon = "🧫", name = "petri_dish", category = "tool" },
	{ icon = "🧬", name = "dna", category = "tool" },
	{ icon = "🔬", name = "microscope", category = "tool" },
	{ icon = "🔭", name = "telescope", category = "tool" },
	{ icon = "📡", name = "satellite_antenna", category = "tool" },
	{ icon = "💉", name = "syringe", category = "tool" },
	{ icon = "💊", name = "pill", category = "tool" },
	{ icon = "🩸", name = "drop_of_blood", category = "tool" },
	{ icon = "🩹", name = "adhesive_bandage", category = "tool" },
	{ icon = "🩺", name = "stethoscope", category = "tool" },
	{ icon = "🚪", name = "door", category = "object" },
	{ icon = "🛗", name = "elevator", category = "tool" },
	{ icon = "🪞", name = "mirror", category = "tool" },
	{ icon = "🪟", name = "window", category = "tool" },
	{ icon = "🛏️", name = "bed", category = "object" },
	{ icon = "🛋️", name = "couch_and_lamp", category = "object" },
	{ icon = "🪑", name = "chair", category = "object" },
	{ icon = "🚽", name = "toilet", category = "object" },
	{ icon = "🪠", name = "plunger", category = "tool" },
	{ icon = "🚿", name = "shower", category = "object" },
	{ icon = "🛁", name = "bathtub", category = "object" },
	{ icon = "🪤", name = "mouse_trap", category = "tool" },
	{ icon = "🪒", name = "razor", category = "tool" },
	{ icon = "🧴", name = "lotion_bottle", category = "tool" },
	{ icon = "🧷", name = "safety_pin", category = "tool" },
	{ icon = "🧹", name = "broom", category = "tool" },
	{ icon = "🧺", name = "basket", category = "object" },
	{ icon = "🧻", name = "roll_of_paper", category = "tool" },
	{ icon = "🪣", name = "bucket", category = "tool" },
	{ icon = "🧼", name = "soap", category = "tool" },
	{ icon = "🪥", name = "toothbrush", category = "tool" },
	{ icon = "🧽", name = "sponge", category = "tool" },
	{ icon = "🧯", name = "fire_extinguisher", category = "tool" },
	{ icon = "🛒", name = "shopping_cart", category = "object" },
	{ icon = "⏰", name = "alarm_clock", category = "object" },
	{ icon = "⌛", name = "hourglass", category = "object" },
	{ icon = "⏳", name = "hourglass_flowing_sand", category = "object" },
	{ icon = "⌚", name = "watch", category = "object" },
	{ icon = "📱", name = "mobile_phone", category = "object" },
	{ icon = "💻", name = "laptop", category = "object" },
	{ icon = "⌨️", name = "keyboard", category = "object" },
	{ icon = "🖥️", name = "desktop_computer", category = "object" },
	{ icon = "🖨️", name = "printer", category = "object" },
	{ icon = "🖱️", name = "computer_mouse", category = "object" },
	{ icon = "💽", name = "computer_disk", category = "object" },
	{ icon = "💾", name = "floppy_disk", category = "object" },
	{ icon = "💿", name = "optical_disk", category = "object" },
	{ icon = "📀", name = "dvd", category = "object" },
	{ icon = "🎥", name = "movie_camera", category = "object" },
	{ icon = "🎞️", name = "film_frames", category = "object" },
	{ icon = "📽️", name = "film_projector", category = "object" },
	{ icon = "🎬", name = "clapper_board", category = "object" },
	{ icon = "📺", name = "television", category = "object" },
	{ icon = "📷", name = "camera", category = "object" },
	{ icon = "📸", name = "camera_with_flash", category = "object" },
	{ icon = "📹", name = "video_camera", category = "object" },
	{ icon = "📼", name = "videocassette", category = "object" },
	{ icon = "🔍", name = "magnifying_glass_tilted_left", category = "object" },
	{ icon = "🔎", name = "magnifying_glass_tilted_right", category = "object" },
	{ icon = "🕯️", name = "candle", category = "object" },
	{ icon = "💡", name = "light_bulb", category = "object" },
	{ icon = "🔦", name = "flashlight", category = "object" },
	{ icon = "🏮", name = "red_paper_lantern", category = "object" },
	{ icon = "🪔", name = "diya_lamp", category = "object" },
	{ icon = "📔", name = "notebook_with_decorative_cover", category = "object" },
	{ icon = "📕", name = "closed_book", category = "object" },
	{ icon = "📖", name = "open_book", category = "object" },
	{ icon = "📗", name = "green_book", category = "object" },
	{ icon = "📘", name = "blue_book", category = "object" },
	{ icon = "📙", name = "orange_book", category = "object" },
	{ icon = "📓", name = "notebook", category = "object" },
	{ icon = "📒", name = "ledger", category = "object" },
	{ icon = "📃", name = "page_with_curl", category = "object" },
	{ icon = "📜", name = "scroll", category = "object" },
	{ icon = "📄", name = "page_facing_up", category = "object" },
	{ icon = "📰", name = "newspaper", category = "object" },
	{ icon = "🗞️", name = "rolled_up_newspaper", category = "object" },
	{ icon = "📑", name = "bookmark_tabs", category = "object" },
	{ icon = "🔖", name = "bookmark", category = "object" },
	{ icon = "🏷️", name = "label", category = "object" },
	{ icon = "💰", name = "money_bag", category = "object" },
	{ icon = "🪙", name = "coin", category = "object" },
	{ icon = "💴", name = "yen_banknote", category = "object" },
	{ icon = "💵", name = "dollar_banknote", category = "object" },
	{ icon = "💶", name = "euro_banknote", category = "object" },
	{ icon = "💷", name = "pound_banknote", category = "object" },
	{ icon = "💸", name = "money_with_wings", category = "object" },
	{ icon = "💳", name = "credit_card", category = "object" },
	{ icon = "🧾", name = "receipt", category = "object" },
	{ icon = "💹", name = "chart_increasing_with_yen", category = "object" },
	{ icon = "✉️", name = "envelope", category = "object" },
	{ icon = "📧", name = "e_mail", category = "object" },
	{ icon = "📨", name = "incoming_envelope", category = "object" },
	{ icon = "📩", name = "envelope_with_arrow", category = "object" },
	{ icon = "📤", name = "outbox_tray", category = "object" },
	{ icon = "📥", name = "inbox_tray", category = "object" },
	{ icon = "📦", name = "package", category = "object" },
	{ icon = "📫", name = "closed_mailbox_with_raised_flag", category = "object" },
	{ icon = "📪", name = "closed_mailbox_with_lowered_flag", category = "object" },
	{ icon = "📬", name = "open_mailbox_with_raised_flag", category = "object" },
	{ icon = "📭", name = "open_mailbox_with_lowered_flag", category = "object" },
	{ icon = "📮", name = "postbox", category = "object" },
	{ icon = "🗳️", name = "ballot_box_with_ballot", category = "object" },
	{ icon = "✏️", name = "pencil", category = "object" },
	{ icon = "✒️", name = "black_nib", category = "object" },
	{ icon = "🖋️", name = "fountain_pen", category = "object" },
	{ icon = "🖊️", name = "pen", category = "object" },
	{ icon = "🖌️", name = "paintbrush", category = "object" },
	{ icon = "🖍️", name = "crayon", category = "object" },
	{ icon = "📝", name = "memo", category = "object" },
	{ icon = "💼", name = "briefcase", category = "object" },
	{ icon = "📁", name = "file_folder", category = "object" },
	{ icon = "📂", name = "open_file_folder", category = "object" },
	{ icon = "🗂️", name = "card_index_dividers", category = "object" },
	{ icon = "📅", name = "calendar", category = "object" },
	{ icon = "📆", name = "tear_off_calendar", category = "object" },
	{ icon = "🗒️", name = "spiral_notepad", category = "object" },
	{ icon = "🗓️", name = "spiral_calendar", category = "object" },
	{ icon = "📇", name = "card_index", category = "object" },
	{ icon = "📈", name = "chart_increasing", category = "object" },
	{ icon = "📉", name = "chart_decreasing", category = "object" },
	{ icon = "📊", name = "bar_chart", category = "object" },
	{ icon = "📋", name = "clipboard", category = "object" },
	{ icon = "📌", name = "pushpin", category = "object" },
	{ icon = "📍", name = "round_pushpin", category = "object" },
	{ icon = "📎", name = "paperclip", category = "object" },
	{ icon = "🖇️", name = "linked_paperclips", category = "object" },
	{ icon = "📏", name = "straight_ruler", category = "object" },
	{ icon = "📐", name = "triangular_ruler", category = "object" },
	{ icon = "✂️", name = "scissors", category = "object" },
	{ icon = "🗃️", name = "card_file_box", category = "object" },
	{ icon = "🗄️", name = "file_cabinet", category = "object" },
	{ icon = "🗑️", name = "wastebasket", category = "object" },
}

local categories = {
	{ name = "All", icon = "🌐" },
	{ name = "face", icon = "😀" },
	{ name = "animal", icon = "🐶" },
	{ name = "food", icon = "🍕" },
	{ name = "travel", icon = "✈️" },
	{ name = "activity", icon = "⚽" },
	{ name = "symbol", icon = "❤️" },
	{ name = "flag", icon = "🏳️" },
	{ name = "gesture", icon = "👋" },
	{ name = "body", icon = "👀" },
	{ name = "object", icon = "💡" },
	{ name = "nature", icon = "🌸" },
	{ name = "tool", icon = "🔧" },
}

function M.pick()
	local current_category = "All"

	local function get_filtered_emojis()
		if current_category == "All" then
			local items = {}
			for _, emoji in ipairs(emoji_list) do
				table.insert(items, { text = emoji.icon .. " " .. emoji.name, icon = emoji.icon, name = emoji.name, category = emoji.category })
			end
			return items
		end
		local filtered = {}
		for _, emoji in ipairs(emoji_list) do
			if emoji.category == current_category then
				table.insert(filtered, { text = emoji.icon .. " " .. emoji.name, icon = emoji.icon, name = emoji.name, category = emoji.category })
			end
		end
		return filtered
	end

	local function get_items()
		return get_filtered_emojis()
	end

	local function format_emoji(item, _)
		return {
			{ item.icon, "SnacksPickerIcon" },
			{ "  " },
			{ item.name, "SnacksPickerTitle" },
		}
	end

	require("snacks").picker({
		title = "Emoji Picker",
		items = get_items(),
		format = format_emoji,
		layout = {
			preset = "default",
			-- No dimensions - let snacks handle it
		},
		keys = {
			["<Tab>"] = {
				function(self)
					local idx = 1
					for i, cat in ipairs(categories) do
						if cat.name == current_category then
							idx = i
							break
						end
					end
					local next_idx = (idx % #categories) + 1
					current_category = categories[next_idx].name
					self:update_items(get_items())
				end,
				desc = "Next category",
			},
		},
		confirm = function(self, item)
			if not item then
				return
			end
			self:close()
			vim.schedule(function()
				vim.api.nvim_put({ item.icon }, "c", true, true)
			end)
		end,
	})
end

function M.setup(opts)
	opts = opts or {}
	local key = opts.key or "<S-e>"
	vim.keymap.set("n", key, function()
		M.pick()
	end, { desc = "Emoji picker" })
end

return M
